### ISSUE TITLE
Install private NPM packages?

### ISSUE THREAD

**Issue by tyler-johnson** [nolanlawson/local-npm#108]
I have some packages in an NPM organization that are private. When I try to install them, I get a 404 error from NPM. I assume this is because they are kept outside of the standard, replicated database so local-npm cannot even know about them.

Knowing the answer is probably no, I figured I'd ask anyway: can private package support be added to local-npm?

**Comment by tyler-johnson** [comment]
I believe the solution is to set a scope specific registry URL so NPM avoids local-npm for private packages:

```sh
npm config set @myscope:registry https://registry.npmjs.org
```

**Comment by nolanlawson** [comment]
So does that mean it's a user-configuration issue? Please reopen if that's not correct.

**Comment by tyler-johnson** [comment]
Yes, but perhaps something could be added about private packages to the documentation?

**Comment by nolanlawson** [comment]
Yes, I would love a PR for that. :)

**Comment by ryan-kimber** [comment]
A much better solution, would be to be able to use local-npm as the registry for the private packages. Otherwise, all of the dependencies for the private module will also bypass local-npm. For a number of our projects (which compose a number of smaller modules into services), this means local-npm gets bypassed for nearly everything.

**Comment by gabrielcsapo** [comment]
@ryan-kimber would you be interested in submitting a PR for this functionality?
