### ISSUE TITLE
Future of this project?

### ISSUE THREAD

**Issue by RnbWd** [nolanlawson/local-npm#112]
I've been using [sinopia](https://github.com/rlidwka/sinopia) for over a year and. I maintain docker container for sinpopia on docker and it's seem like the it's the most used npm cache repo on docker.

But it looks like the lead dev abandonded the project - it's an extremely complicated express app - and I need to decide whether or not to take that over or work on something like this that seems promising and does (almost) the same thing. I don't know how rlidwka wrote it - but I usually get 10x the speed of npm - I use docker to proxy in front of nginx caching servers using http/2 / lets encrypt - but it's all zero-config. I and get it up and running with a gogs in 10 minutes. (unlimited private github repos and npm repos / caching on $5 digital ocean servers)

Sinopia was built to run locally - it's a command line app technically.  It's fast (maybe faster than this). But I have no idea how it works. Not sure if you're familiar with sinopia - but if this repo is active and you're interested in some help i'd be willing to contribute

**Comment by nolanlawson** [comment]
Thanks for the issue! I actually never intended local-npm to be a sinopia replacement, although it's been a much-requested feature. I plan on continuing to develop local-npm exactly as it is (a dumb mirror in front of npm), but I encourage anybody to fork the codebase and learn from what I did in order to make their own sinopia. :)

As it turns out, I think local-npm's approach has some huge advantages over sinopia when it comes to "build your own npm," because sinopia reimplemented nearly all of npm's registry from scratch, whereas local-npm leverages PouchDB to simply sync npm's CouchDB. Hence we get replication for free as well as a lot of behavioral parity.

Closing this issue because I consider it out of scope for local-npm, but again, I encourage anybody interested in this idea to fork! :)
