### ISSUE TITLE
Packages get stuck with out-of-date versions

### ISSUE THREAD

**Issue by mattkrick** [nolanlawson/local-npm#79]
For a certain package, local-npm isn't showing the latest available version from npm. Is falling out of async an issue? Is there any easy way to rescan to get it back?

**Comment by nolanlawson** [comment]
Hmm, normally that should be taken care of automatically. Can you look at the `local-npm` logs and verify that it's still replicating from the main npm registry?

Alternatively, you can clear out all the data by 1) stopping local-npm, 2) clearing out the data directory especially `skimdb`, and then 3) restarting.

**Comment by mlegenhausen** [comment]
Have the same problem. Still replicating but some packages seem out of sync. In my case it was `js-extend` (a depencency of pouchdb).

**Comment by nolanlawson** [comment]
Hm, could either of you post the last output from the logs? Usually you can see something like 

    local-npm-0 (out): Replicating skimdb, last_seq is: 651129 (100%)

Which e.g. indicates that the last change that came in was `651129`, which you can check by querying: https://skimdb.npmjs.com/registry/_changes?limit=1&since=651129.

If you increase that `limit`, you can see if there are newer modules that are indeed not replicating for some reason.

**Comment by mlegenhausen** [comment]
Am already at seqId 651889 and no more outstanding changes to sync and still `js-extend` only version 0.0.2 available (which was the last before 1.0.1). Could you find out the seqId where js-extend was updated? So I can test out my result for the query.

I think deleting the database and resyncing will solve the problem, but that is really annoying when you need to sync 700mb and hopefully it is not a bug in the persistence layer of pouchdb syncing mechanism.

**Comment by mlegenhausen** [comment]
Ok I get more and more packages out of sync. I will remove my local database and replicate again. Is there any way to collect error information that is useful for you?

**Comment by nolanlawson** [comment]
This actually does sound like a bug in the persistence layer. However, I've been using `local-npm` on my machine (Mac OS X) for months and never seen such a bug. :confused: In fact I often publish a module, then I check `npm info modulename` and it shows the latest version within a few seconds...

If you can provide any steps to reproduce, that would be helpful, but I have no idea why this is happening. Maybe the error logs for `local-npm` show something interesting?

As for how to get the latest `seq` number for a certain doc, you can usually use `_changes` with `doc_ids`, but it looks like npm's version of CouchDB doesn't support that. so I actually don't know how to find it without getting all the changes and searching in-memory.

**Comment by mlegenhausen** [comment]
Of cause local-npm is awesomely fast synced with the npm registry. I just guessed maybe this happens between restarts of my machine or so on.

But guesses don't help that much here. I updated to the latest node and local-npm version and resynced all again and activated debug logging. I will keep an eye on it and maybe I find something in the logs.

**Comment by latentflip** [comment]
FWIW I've just run into the same issue. My logs say everything is running, and that I'm up to date with the last_seq number, but if I try and install destroy@1.0.4 (https://www.npmjs.com/package/destroy) I get a failure.

**Comment by nolanlawson** [comment]
@latentflip What happens when you run `npm info destroy`? And what failure do you get?

Another way to debug this is to browse around in the Fauxton UI of the PouchDB database, which is at http://127.0.0.1:16984/_utils. Click on `skimdb`, find the package by name, and see what data is synced.

**Comment by mlegenhausen** [comment]
Again out of sync after 14 days of usage. Nothing in the error logs. Debug logs are pretty big don't know what to look for. Had one or two restarts during this time.

Using Node 5.4.1 and latest local-npm version.

**Comment by nolanlawson** [comment]
The thing to look for in the logs is the "last_seq". Then compare that to the last_seq from the CouchDB in skimdb, which you can find this way: https://skimdb.npmjs.com/registry/_changes?limit=1&descending=true

(I.e. that link will show you the most recently published module, and the sequence number associated with it. If your local last_seq is lower than that, then replication has stalled for some reason.)

Again, FWIW, I have used local-npm as my primary npm for the past ~6 months so and never had an issue. I'm on OS X Yosemite with Node 5.3.0. Sometimes I will even publish a module and then immediately install it afterwards; local-npm is that fast.

**Comment by mattkrick** [comment]
Fwiw this only happened the once and it healed itself without me doing
anything (although the package in question got a version bump, so maybe
that triggered a refetch). Probably too early to suggest a fix since we
still don't know the cause, but maybe a nice `local-npm --manual
package@version` that rimrafs the package in question would be useful.

**Comment by jgog** [comment]
Hey guys,

I am facing the same issue, trying to update `react` but the `local-npm` is out of date. The logs show everything is fine:
```
node-0 Replicating skimdb, last_seq is: 711436 (100%)
node-0 Replicating skimdb, last_seq is: 711443 (100%)
node-0 Replicating skimdb, last_seq is: 711446 (100%)
node-0 Replicating skimdb, last_seq is: 711450 (100%)
```

Here are the screens:
![screen shot 2016-02-01 at 10 18 20 pm](https://cloud.githubusercontent.com/assets/971411/12724053/2015b92e-c932-11e5-9cb7-01d014044d01.png)

![screen shot 2016-02-01 at 10 18 18 pm](https://cloud.githubusercontent.com/assets/971411/12724054/207ec2a2-c932-11e5-81f2-4433bbd9f6d6.png)


Any fix?

**Comment by jgog** [comment]
Hey @nolanlawson any fix for this, I still have react@0.14.6 on my local!

**Comment by mlegenhausen** [comment]
7 days, again packages out of sync. I am definitely on sync and when fetching the package witch `https://skimdb.npmjs.com/registry/<package_name>` I get already the new version from the `skimdb`, but this version was not replicated to my `local-npm` instance.

In this case the package is `babel-register`. I find out that the sequence number of the package was `734745`. In my `local-npm` logs I find two sequence number between this package should be syned. Which I checked via `https://skimdb.npmjs.com/registry/_changes?since=734579&limit=197`.

```
Replicating skimdb, last_seq is: 734579 (100%)
Replicating skimdb, last_seq is: 734848 (100%)
```

But I also found this in my error logs. Sadly I have no timestamps prepended before my logs, so I can not guarantee that this error is related to the bug.

```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
```

@nolanlawson Would it be possible to fix only this package by copying the data from `skimdb` without having a conflict on next package update?

**Comment by nolanlawson** [comment]
I'm sorry y'all ran into this, but I've never been able to reproduce on my own machine. Based on the screenshots, though, I can definitely confirm that it's an issue with the PouchDB replication.

My guess is that maybe this only happens when modules are unpublished? I'm not familiar with the release schedule of React, but maybe they unpublished, but the npm CouchDB changes feed doesn't actually propagate those changes. Other than that; I'm out of ideas.

**Comment by MarufSarker** [comment]
This problem seems like happening regularly. A few days back had this issue, and had to switch back to regular npm registry. 

Again, today it happened (today's package: postcss-discard-duplicates). I was getting the 2.0.0 for every try (with sync status 100%). 

Then I removed all files and folders created by ```local-npm``` and re-started the server from 0.00%, everything became normal and the 2.0.1 was being installed. 

Though I don't know what is/are causing the problem, but seems like the new version of npm packages are not being updated as they are available in npm site/registry.

(```i've no knowledge, so just a blank thought```) Is the registry/database ```local-npm``` using is different from the registry/database https://registry.npmjs.org is using? 

If so, then it would become hard to keep track of every package's latest version and being installed version by ```local-npm```.

(```another semi-blank thought```) But, from my scenario it doesn't seem like that the registries/databases are different, as just after removing and re-starting the server from 0.00% solved the issue. 
Something is ignoring to check for remote update/version while something is available in the local database, may be some small function who checks for version update/comparison/you know the best :)
May be if somehow some updates get corrupted, ```local-npm``` skips those and later on thinks those are okay.

BTW, 
Thanks for your amazing package :)

**Comment by nolanlawson** [comment]
Really sorry to say I'm not sure what's going on here, unless we have a test to reproduce. :/ PRs would be welcome if anyone can figure this out, though.

**Comment by MarufSarker** [comment]
(```just in-case it become handy```)

Is this behavior somewhat normal, going from 100%(nearly) to back down to 50%(nearly)? 

I'm not being concerned about the percentages, but about the ```last_seq```. They followed as ```837998``` > 837999 > 836836 > ```456509```

![local-npm](https://cloud.githubusercontent.com/assets/10809140/13576140/62a3e69a-e4b6-11e5-81d2-c2e8c22f7ae4.png)

and after some time it went back to 100% again,

![local-npm-2](https://cloud.githubusercontent.com/assets/10809140/13576391/b04ad16e-e4b7-11e5-8dd1-2c80b357d389.PNG)


(```in case the question comes being the above scenario as normal```)
If the scenario is normal and someone says that, I should know it as a normal scenario, the answer would be that, most of the time I use ```local-npm``` in a hidden powershell window, so I generally (most of the time) do not follow the logs.


(in case someone wants to know, how to run local-npm in a hidden powershell window)
```powershell.exe -windowstyle hidden -command local-npm``` is the command, I use.


Thanks :)

**Comment by nolanlawson** [comment]
In case anyone wants a temporary solution to this problem (for OSX):

```
pm2 stop all
rm -fr ~/.local-npm/skimdb/
pm2 start all
```

**Comment by TehShrike** [comment]
I just ran into this issue on OSX with `babel-types` - I'm unable to install 6.7.2.  I note that 6.7.1 was apparently unpublished.

**Comment by mattkrick** [comment]
This happened to me again with 5 packages, all babel packages at v6.7.2, so I had the chance to experiment.

The quickest way to make things right:
- goto: http://127.0.0.1:16984/_utils/#/database/skimdb/_all_docs
- create an admin account. Updates & deletes fail if you don't...which is a bug I believe & possibly the root cause of this. @nolanlawson can you confirm that if no admin account exists, then all users have admin rights? Also, if you don't use the admin account for ~5 mins, then you get the same error & you have to recreate the admin account... definitely something weird going on here
- search for the package in question
- delete the doc
- now, instead of a 304 you'll get a 200 for that package & it'll pull the fresh version from npm

Idea for a PR:
I couldn't find it anywhere in the code, but if there's a place that listens for the result from npm, we could do the following:

- if error message from npm contains "No compatible version found" then delete the doc in question, & retry the fetch

**Comment by nolanlawson** [comment]
Hi everyone, sorry for the radio silence on this issue. I think this might actually be a bug in the PouchDB replication algorithm; I suspect it's the same issue as https://github.com/pouchdb/pouchdb/pull/5055.

I will push a release to PouchDB, then update this package's dependency version, and then we'll cross our fingers and hope it doesn't come up again. If if does, I have a local installation that repros the issue (yup, ran into it myself!), so once I get a spare moment I will be able to investigate.

**Comment by jgog** [comment]
@nolanlawson sounds like a plan! 🤘

**Comment by nolanlawson** [comment]
PouchDB 5.3.2 is now out. OSX users: if you could please upgrade using:

```
pm2 stop all
rm -fr ~/.local-npm/skimdb
npmrc default
npm remove -g local-npm
npm install -g local-npm
npmrc local
pm2 start all
```

Please re-test and let me know if this issue comes up again.

**Comment by mlegenhausen** [comment]
Thanks will give a try

**Comment by mlegenhausen** [comment]
Feedback after 11 days still in sync.

**Comment by mattkrick** [comment]
all good on my end, too. i'll close for now to keep the issue tracker clean. big thanks to @nolanlawson for fixing this bug that was nearly impossible to reproduce!

**Comment by nolanlawson** [comment]
Yup, still in sync for me too. Please reopen if it's still an issue, but otherwise it looks like the fix was on the PouchDB side of things.

**Comment by tonidy** [comment]
I just ran into this issue on Windows 10 with [balance-match](https://www.npmjs.com/package/balanced-match) package. Local-npm has 0.4.0 but in npmjs the latest version is 0.4.1

I have checked local-npm version and it was latest version (1.5.8). My problem have solved with delete skimdb and reinstall local-npm. I think local-npm should have some option to push metadata from registry to specific module. What do you think @nolanlawson ?

**Comment by nolanlawson** [comment]
Can you tell me which version of PouchDB it's using? My assumption about this bug being fixed was based on PouchDB being updated to the latest version. (5.3.2)

**Comment by tonidy** [comment]
Current version of PouchDB,

```
local-npm@1.5.8 npm\node_modules\local-npm
+-- pouchdb@5.3.2
```

Let's me see if this issue still happen or not. Thanks

**Comment by DimitryDushkin** [comment]
Same for min-document. Current version 2.19.0, but skimdb has only 2.18.0
