### ISSUE TITLE
Bind local-npm against remote Sinopia instance

### ISSUE THREAD

**Issue by subesokun** [nolanlawson/local-npm#80]
Hi, I'm very interested in using local-npm but currently I'm facing the problem that our "master" npm registry is based on Sinopia which hosts bunch of private NPM packages and it's currently difficult to change that. Is it somehow possible to bind local-npm against Sinopia (or similar solutions that provide only a fullfatdb)? I'd love to use local-npm so that I can work also offline.

Thanks a lot in advance!

**Comment by nickcolley** [comment]
Hey @subesokun !

Looks like you can configure what registery local-npm uses with the CLI options: https://github.com/nolanlawson/local-npm#command-line-options

So maybe
```bash
$ local-npm --remote http://localhost:4873  --remote-skim http://localhost:4873/skimdb
```

Then set your npm client to hit local-npm so you'd end up with.

npm (client) -> local-npm -> sinopia -> default-registry

Hope this helps

Nick

**Comment by nolanlawson** [comment]
Thanks @nickcolley, this is definitely the right way to do it, but unfortunately Sinopia can't be supported (nor can [Nexus npm](http://blog.sonatype.com/2014/10/npm-registry-support-for-all/) or similar npm-esque registries), because *they are not built using PouchDB/CouchDB*.

Therefore the problem will come in when you try to do e.g. `--remote-skim http://localhost:4873/skimdb`, because Sinopia has no Couch-based skimdb.

Anyway, sorry about that!

**Comment by subesokun** [comment]
Hi @nolanlawson, thanks for your feedback. I've feared already that this won't be possible due to missing PouchDB/CouchDB in Sinopia but thanks for clarifying.
